# Generated by Django 2.0.7 on 2018-07-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archi', '0002_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='POST_TITLE', max_length=140),
        ),
    ]
