# Generated by Django 2.0.7 on 2018-07-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archi', '0003_auto_20180716_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
